version: 2
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: echo "Installing dependencies..."
      - run: npm install
      - run: echo "Building the project..."
      - run: CI=true npm run build # The env var only has meaning if you have an implementation in place within the project.
  test:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: echo "Installing dependencies..."
      - run: npm install
      - run: echo "Running test suite"
      - run: npm run test
workflows:
  version: 2
  pipeline:
    jobs:
      - build
      - test
